# Generated by Django 4.2.10 on 2024-02-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('fundraising_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('team_option', models.CharField(max_length=20)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('under_18', models.BooleanField()),
                ('mailing_address', models.TextField()),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
