# Generated by Django 4.2.10 on 2024-02-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_participant_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='participant',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
