# Generated by Django 4.2.10 on 2024-02-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_participant_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='donation_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fundraising_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
