# Generated by Django 4.2.10 on 2024-02-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_participant_donation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='under_18',
            field=models.BooleanField(default=False),
        ),
    ]
