# Generated by Django 4.2.10 on 2024-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_participant_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
