# Generated by Django 4.2.10 on 2024-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_participant_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='donation_amount',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='fundraising_goal',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='mailing_address',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team_option',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='under_18',
        ),
    ]
