# Generated by Django 5.0.3 on 2024-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_participant_donation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='fundraising_goal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
