# Generated by Django 5.0.3 on 2024-04-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_participant_fundraising_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
