# Generated by Django 4.2.10 on 2024-04-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_participant_team_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddField(
            model_name='participant',
            name='is_team_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='motivation_fight_suicide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='motivation_mental_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='motivation_support_mental_health',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fundraising_goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
