# Generated by Django 4.2.10 on 2024-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='donation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
