# Generated by Django 4.2.10 on 2024-05-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_participant_donation_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('bronze', 'Bronze Community Supporter'), ('silver', 'Silver Hope Advocate'), ('gold', 'Gold Lifesaver Leader'), ('platinum', 'Platinum Empathy Champion'), ('titanium', 'Titanium Community Ambassador')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField()),
            ],
        ),
    ]
